In [ ]:
# Go up

import os

os.chdir('..')

# Binarizer

https://sklearner.com/scikit-learn-binarizer/

In [ ]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import Binarizer
import numpy as np

# generate continuous data
X, _ = make_classification(
    n_samples=100,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    random_state=1,
)
X = X * 10  # scale data to have wider range of values

# configure the binarizer
binarizer = Binarizer(threshold=0.0)

# transform the dataset
binary_X = binarizer.fit_transform(X)

# show before and after transformation
print("Before Binarization:")
print(X[:5])
print("After Binarization:")
print(binary_X[:5])

Before Binarization:
[[ 13.00227169  -7.85653903]
 [ 14.41844252  -5.60085539]
 [ -8.47924448 -13.66213235]
 [ -7.22150149 -14.11294144]
 [-12.72214654   2.59451061]]
[[ 13.00227169  -7.85653903]
 [ 14.41844252  -5.60085539]
 [ -8.47924448 -13.66213235]
 [ -7.22150149 -14.11294144]
 [-12.72214654   2.59451061]]
After Binarization:
[[1. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [5]:
import numpy as np

a = np.hstack((binary_X, X))
a

array([[  1.        ,   0.        ,  13.00227169,  -7.85653903],
       [  1.        ,   0.        ,  14.41844252,  -5.60085539],
       [  0.        ,   0.        ,  -8.47924448, -13.66213235],
       [  0.        ,   0.        ,  -7.22150149, -14.11294144],
       [  0.        ,   1.        , -12.72214654,   2.59451061],
       [  1.        ,   1.        ,   7.8694271 ,   9.42948786],
       [  1.        ,   0.        ,   8.16957655, -11.24787067],
       [  1.        ,   0.        ,  16.82270703,  -6.75968771],
       [  0.        ,   0.        , -10.72233433,  -7.70151304],
       [  0.        ,   1.        ,  -0.65392972,  11.12573764],
       [  0.        ,   1.        , -13.32329524,   6.02456713],
       [  0.        ,   1.        ,  -6.96371397,   9.63827158],
       [  1.        ,   1.        ,   8.23406141,   7.56192605],
       [  0.        ,   0.        , -15.15553398,  -1.58048526],
       [  0.        ,   1.        ,  -7.89717763,  17.03479729],
       [  1.        ,   1